
device: 'cuda'
resume_training: False

model:
  backbone: 'resnet50'
  head_name: 'DeepLabV3Plus'
  output_stride: 16
  alpha: 1
  gamma: 1

Train:
  batch_size: 12
  shuffle: True
  num_workers: 8
  pin_memory: True
  epochs: 100
  lr: 1e-3
  dataset:
    name: pascalvoc
    num_classes: 21
    image_dir: 'dataset/VOCdevkit/VOC2012/JPEGImages'
    anno_dir: 'dataset/VOCdevkit/VOC2012/SegmentationClass'
    ids_path: 'dataset/VOCdevkit/VOC2012/ImageSets/Segmentation'
  transforms:
    image_shape: [3, 512, 512]
    augmentation: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]


Val:
  batch_size: 6
  shuffle: False
  num_workers: 4
  pin_memory: True
  eval_step: 5
  dataset:
    name: pascalvoc
    num_classes: 21
    image_dir: 'dataset/VOCdevkit/VOC2012/JPEGImages'
    anno_dir: 'dataset/VOCdevkit/VOC2012/SegmentationClass'
    ids_path: 'dataset/VOCdevkit/VOC2012/ImageSets/Segmentation'
  transforms:
    image_shape: [3, 512, 512]
    augmentation: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

Debug:
  model: 'debugs/model'
  dataset: 'debugs/dataset'
  log_dir: 'logs'
  tensorboard: "exps/tensorboard"