
device: 'cuda'
resume_training: False

model:
  backbone: 'reset50'

Train:
  dataset:
    name: pascalvoc
    num_classes: 21
    image_dir: 'dataset/VOCdevkit/VOC2012/JPEGImages'
    anno_dir: 'dataset/VOCdevkit/VOC2012/SegmentationClass'
    ids_path: 'dataset/VOCdevkit/VOC2012/ImageSets/Segmentation'
  transforms:
    image_shape: [3, 513, 513]
    augmentation: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]


Valid:
    dataset:
    name: pascalvoc
    image_dir: dataset/icdar2015/train/images
    anno_dir: dataset/icdar2015/train/gt
    transforms:
      image_shape: [3, 768, 768]
      augmentation: True
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

Debug:
  model: 'debugs/model'
  dataset: 'debugs/dataset'