
device: 'cuda'
resume_training: False

model:
  backbone: 'resnet50'
  head_name: 'deeplabv3plus'
  output_stride: 16
  alpha: 0.5
  gamma: 2.0

Train:
  batch_size: 14
  shuffle: True
  num_workers: 8
  pin_memory: True
  total_itrs: 30000
  lr: 0.01
  weight_decay: 1e-4
  step_size: 10000
  dataset:
    name: pascalvoc
    num_classes: 21
    image_dir: 'dataset/VOCdevkit/VOC2012/JPEGImages'
    anno_dir: 'dataset/VOCdevkit/VOC2012/SegmentationClass'
    ids_path: 'dataset/VOCdevkit/VOC2012/ImageSets/Segmentation'
  transforms:
    image_shape: [3, 513, 513]
    augmentation: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]


Val:
  batch_size: 8
  shuffle: False
  num_workers: 4
  pin_memory: False
  eval_step: 100
  dataset:
    name: pascalvoc
    num_classes: 21
    image_dir: 'dataset/VOCdevkit/VOC2012/JPEGImages'
    anno_dir: 'dataset/VOCdevkit/VOC2012/SegmentationClass'
    ids_path: 'dataset/VOCdevkit/VOC2012/ImageSets/Segmentation'
  transforms:
    image_shape: [3, 513, 513]
    augmentation: False
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

Debug:
  debug_mode: True
  model: 'debugs/model'
  dataset: 'debugs/dataset'
  log_dir: 'logs'
  tensorboard: "exps/tensorboard"
  ckpt_dirpath: "exps/weights"
  train: 'exps/training'
  val: 'exps/valid'
  prediction: exps/prediction
  debug_idxs: [1,2,3,4,5,6,7,8,9,10]